"""adding feedback tables

Revision ID: 40dbe60d7b4a
Revises: dec64270d567
Create Date: 2021-03-17 00:09:00.314588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40dbe60d7b4a'
down_revision = 'dec64270d567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_from_user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_about_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_about_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feedback_from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedbacks_feedback_about_user_id'), 'user_feedbacks', ['feedback_about_user_id'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_feedback_from_user_id'), 'user_feedbacks', ['feedback_from_user_id'], unique=False)
    op.create_table('feedback_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_rating_type', sa.String(), nullable=True),
    sa.Column('feedback_rating_score', sa.Integer(), nullable=True),
    sa.Column('user_feedback_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_feedback_id'], ['user_feedbacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_ratings_user_feedback_id'), 'feedback_ratings', ['user_feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_ratings_user_feedback_id'), table_name='feedback_ratings')
    op.drop_table('feedback_ratings')
    op.drop_index(op.f('ix_user_feedbacks_feedback_from_user_id'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_user_feedbacks_feedback_about_user_id'), table_name='user_feedbacks')
    op.drop_table('user_feedbacks')
    # ### end Alembic commands ###
