"""creating new personal charactirstics tables

Revision ID: 79de44e631b0
Revises: f9cba50da292
Create Date: 2021-03-25 00:01:05.391130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79de44e631b0'
down_revision = 'f9cba50da292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('hobby_name', sa.String(), nullable=True),
    sa.Column('engagement_level', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_hobbies_user_id'), 'user_hobbies', ['user_id'], unique=False)
    op.create_table('user_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('interest_name', sa.String(), nullable=True),
    sa.Column('interest_level', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interest_user_id'), 'user_interest', ['user_id'], unique=False)
    op.add_column('user_expertises', sa.Column('expertise_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_expertises', 'expertise_level')
    op.drop_index(op.f('ix_user_interest_user_id'), table_name='user_interest')
    op.drop_table('user_interest')
    op.drop_index(op.f('ix_user_hobbies_user_id'), table_name='user_hobbies')
    op.drop_table('user_hobbies')
    # ### end Alembic commands ###
