"""add service_provider column to users table

Revision ID: cb1e613ed84d
Revises: 79de44e631b0
Create Date: 2021-03-25 00:16:44.723312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1e613ed84d'
down_revision = '79de44e631b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('service_provider', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'service_provider')
    # ### end Alembic commands ###
