"""creating service propostion tables

Revision ID: f9cba50da292
Revises: 40dbe60d7b4a
Create Date: 2021-03-23 01:21:32.429583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cba50da292'
down_revision = '40dbe60d7b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposition_owner_id', sa.Integer(), nullable=False),
    sa.Column('proposition_status', sa.Enum('ACTIVE', 'CLOSED', 'CANCELED', name='servicepropositionstatus'), nullable=True),
    sa.Column('service_type', sa.Enum('CONSULTING', 'TRAINING', 'TEACHING', 'COACHING', name='servicetype'), nullable=True),
    sa.Column('proposition_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposition_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_services_proposition_owner_id'), 'proposed_services', ['proposition_owner_id'], unique=False)
    op.create_table('proposed_service_content_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_content_type', sa.Enum('RECORDED_CONTENT', 'WRITTEN_CONTENT', 'ONLINE_PERSONAL_MEETING', 'ONLINE_CONFERENCE', 'FACE_TO_FACE_MEETING', 'FACE_TO_FACE_CONFERENCE', name='servicecontenttype'), nullable=True),
    sa.Column('proposed_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposed_service_id'], ['proposed_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposed_service_content_types')
    op.drop_index(op.f('ix_proposed_services_proposition_owner_id'), table_name='proposed_services')
    op.drop_table('proposed_services')
    # ### end Alembic commands ###
