from enum import Enum


class ServiceType(Enum):
    CONSULTING = 'CONSULTING'
    TRAINING = 'TRAINING'
    TEACHING = 'TEACHING'
    COACHING = 'COACHING'


class ServiceContentType(Enum):
    RECORDED_CONTENT = 'RECORDED_CONTENT'
    WRITTEN_CONTENT = 'WRITTEN_CONTENT'
    ONLINE_PERSONAL_MEETING = 'ONLINE_PERSONAL_MEETING'
    ONLINE_CONFERENCE = 'ONLINE_CONFERENCE'
    FACE_TO_FACE_MEETING = 'FACE_TO_FACE_MEETING'
    FACE_TO_FACE_CONFERENCE = 'FACE_TO_FACE_CONFERENCE'


class ServicePropositionStatus(Enum):
    ACTIVE = 'ACTIVE'
    CLOSED = 'CLOSED'
    CANCELED = 'CANCELED'
